### ISSUE TITLE
Error on Local file read/write component

### ISSUE THREAD

**Issue by linaCardozo** [X-Wei/flutter_catalog#127] opened 2022-05-21 03:12 UTC
In the Local file read/write component which is inside Persistence, when the user hasn't input some text and saved it but clicks on Load, an error text is shown (the following image illustrates that):

![1](https://user-images.githubusercontent.com/42348727/169633088-f8235682-ee2f-4ceb-b63a-074351037f4b.png)

**Proposed Solution:** When the user hasn't saved some text, you could show a dialog indicating the user, that he must save something first in order to load the saved text.

**Comment by X-Wei** [comment] 2022-06-06 19:36
Agree the UI is not great, I wrote like this to minimize code that is unrelated to the "file read/write" topic.

I'm closing this for now as it is not a bug per se. But feel free to create a PR to fix this.

**Closed by X-Wei** 2022-06-06 19:36 UTC
